### ISSUE TITLE
### To-Do List for the next Steps:

### ISSUE THREAD

**Issue by TeyUs** [adessoTurkey/ios-sample-app-swiftui#27]
### To-Do List for the next Steps:
_Add yourself in which item you want to work on by adding @ next to it._

## Development

- [ ] Search for which requests we can obtain from the API [Docs URL](https://docs.coinapi.io/)
- [ ] Create a request/response model for fetching coin list @adesso-said 
- [ ] Record users choice to favorite/unfavorite coins. @TeyUs

## Improvements
- [ ] Refactoring Home Screen @egesucu 
- [ ] Refactoring Favorite Screen
- [ ] Refactoring Settings Screen
- [ ] Refactoring Coin Detail Page

_Originally posted by @egesucu in https://github.com/adessoTurkey/ios-sample-app-swiftui/issues/18#issuecomment-1481042035_
